name: serverless_chatbot
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.0
  uuid: ^3.0.7
  http: ^0.13.5
  record: ^4.4.3
  path_provider: ^2.0.11
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1
  flutter_signin_button: ^2.0.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  just_audio: ^0.9.31


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  injectable_generator: ^2.1.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SquareSlabserif
      fonts:
      - asset: assets/fonts/Square-Slabserif/0410EU27.ttf
        weight: 100
      - asset: assets/fonts/Square-Slabserif/0411EU27.ttf
        weight: 500
      - asset: assets/fonts/Square-Slabserif/0412EU27.ttf
        weight: 900